import type { Template, SourceRecord, Contract, ContractFields, RogueTemplate } from "./types";
import { runChecks } from "./clause-checker";
import { computeRouting } from "./routing-rules";
import { isAcceptedLaw } from "./policy-config";

export const LIGHT_ENTITIES = [
  "Light ApS (Denmark)",
  "Light Ltd (United Kingdom)",
  "Light Inc. (US Delaware)",
] as const;

export const TEMPLATES: Template[] = [
  {
    id: "nda_v3_1",
    name: "Mutual NDA",
    version: "v3.1",
    type: "NDA",
    risk: "low",
    ownerTeam: "Legal",
    jurisdictions: ["Denmark", "United Kingdom", "EU member states"],
    description:
      "Two-way confidentiality agreement with EU and UK defaults. Used early in sales conversations, with candidates, and with partners.",
    clauseRules: [
      {
        key: "governing_law",
        label: "Governing law",
        expected: "Denmark, UK, or EU member state",
        predicate: (f) => isAcceptedLaw(f.governingLaw),
        observed: (f) => f.governingLaw ?? "Denmark",
        severity: "warn",
        reason: "Non-EU and non-UK governing law requires Legal review for enforceability.",
      },
      {
        key: "term_months",
        label: "Term",
        expected: "24 months",
        predicate: (f) => (f.termMonths ?? 24) <= 36,
        observed: (f) => `${f.termMonths ?? 24} months`,
        severity: "info",
        reason: "Standard term is 24 months. Terms over 36 months flagged for awareness.",
      },
      {
        key: "mutual_obligations",
        label: "Mutual obligations",
        expected: "Yes (both parties bound)",
        predicate: () => true,
        observed: () => "Mutual",
        severity: "info",
        reason: "Mutual NDAs bind both parties equally. Unilateral NDAs are a separate template.",
      },
      {
        key: "residuals_carve_out",
        label: "Residuals clause",
        expected: "Not included (Light standard)",
        predicate: () => true,
        observed: () => "Not included",
        severity: "info",
        reason: "Residuals clauses are non-standard at Light. Any inbound NDA with residuals routes to Legal.",
      },
    ],
    docusignFeatures: {
      qesRequired: false,
      smsVerification: false,
      witnessRequired: false,
      powerFormCapable: true,
      bulkSendCapable: true,
      expiryDays: 14,
      reminderDays: [3, 7],
      signingOrder: "parallel",
    },
    conditionalSections: [
      {
        id: "uk_jurisdiction_exhibit",
        label: "UK jurisdiction addendum",
        description: "Adds UK-specific governing law and dispute resolution clauses.",
        appliesWhen: (f) => /united kingdom|england|uk/i.test(f.governingLaw ?? ""),
      },
    ],
    anchorTags: ["\\sig:counterparty\\", "\\date:counterparty\\", "\\sig:light\\", "\\date:light\\"],
    versionHistory: [
      { version: "v3.1", releasedAt: "2026-02-14", status: "current", author: "Sara Friis (counsel)", changeNote: "Current. Added UK jurisdiction addendum, residuals carve-out tightened." },
      { version: "v3.0", releasedAt: "2025-09-08", status: "deprecated", deprecatedAt: "2026-02-14", author: "Sara Friis (counsel)", changeNote: "Major rewrite for GDPR alignment. Replaced one-sided NDA boilerplate with mutual default." },
      { version: "v2.4", releasedAt: "2025-03-22", status: "archived", deprecatedAt: "2025-09-08", author: "Outside counsel", changeNote: "Earlier mutual NDA from the company's first year." },
    ],
  },
  {
    id: "msa_v4_2",
    name: "MSA",
    formalName: "Master Services Agreement",
    version: "v4.2",
    type: "MSA",
    risk: "medium",
    ownerTeam: "Sales",
    jurisdictions: ["Denmark", "United Kingdom", "United States"],
    description:
      "Standard customer agreement for all commercial deals. Approved by Legal February 2026. Any deviation routes to Legal automatically.",
    clauseRules: [
      {
        key: "payment_terms",
        label: "Payment terms",
        expected: "Net 30",
        predicate: (f) => (f.paymentTermsDays ?? 30) <= 30,
        observed: (f) => `Net ${f.paymentTermsDays ?? 30}`,
        severity: "warn",
        reason: "Standard payment terms are Net 30. Longer terms impact cash flow and require Finance review.",
      },
      {
        key: "liability_cap",
        label: "Liability cap",
        expected: "€500,000",
        predicate: (f) => !f.liabilityCapUnlimited && (f.liabilityCapEur ?? 500_000) >= 500_000,
        observed: (f) => (f.liabilityCapUnlimited ? "Unlimited" : `€${(f.liabilityCapEur ?? 500_000).toLocaleString()}`),
        severity: "block",
        reason: "Liability cap below €500k or unlimited liability is non-standard and requires Legal approval.",
      },
      {
        key: "governing_law",
        label: "Governing law",
        expected: "Denmark (Light ApS) or selected Light entity jurisdiction",
        predicate: (f) => isAcceptedLaw(f.governingLaw),
        observed: (f) => f.governingLaw ?? "Denmark",
        severity: "warn",
        reason: "Non-EU and non-UK governing law requires Legal review for enforceability.",
      },
      {
        key: "term_months",
        label: "Initial term",
        expected: "12 months",
        predicate: (f) => (f.termMonths ?? 12) <= 12,
        observed: (f) => `${f.termMonths ?? 12} months`,
        severity: "info",
        reason: "Standard initial term is 12 months. Multi-year commitments require Finance awareness for revenue recognition.",
      },
      {
        key: "auto_renew",
        label: "Auto-renew",
        expected: "Yes (12 months)",
        predicate: (f) => f.autoRenew !== false,
        observed: (f) => (f.autoRenew === false ? "No auto-renew" : "Yes, 12 months"),
        severity: "info",
        reason: "Standard MSA auto-renews unless customer opts out 60 days before term end.",
      },
    ],
    docusignFeatures: {
      qesRequired: false,
      smsVerification: false,
      witnessRequired: false,
      powerFormCapable: false,
      bulkSendCapable: false,
      expiryDays: 30,
      reminderDays: [3, 7, 14],
      signingOrder: "sequential",
    },
    conditionalSections: [
      {
        id: "qes_for_large_eu",
        label: "eIDAS QES identity verification",
        description: "Required for EU contracts above €100k ARR for advanced electronic signature.",
        appliesWhen: (f) => (f.contractValueEur ?? 0) >= 100_000 && isAcceptedLaw(f.governingLaw),
      },
      {
        id: "service_levels_exhibit",
        label: "Service Level Exhibit (Exhibit A)",
        description: "Standard SLAs as a separate exhibit. Always attached.",
        appliesWhen: () => true,
      },
      {
        id: "dpa_exhibit",
        label: "Data Processing Agreement (Exhibit B)",
        description: "GDPR EU SCCs attached when Light processes customer personal data.",
        appliesWhen: (f) => f.dpaRequired !== false,
      },
    ],
    anchorTags: [
      "\\sig:counterparty\\",
      "\\name:counterparty\\",
      "\\title:counterparty\\",
      "\\date:counterparty\\",
      "\\sig:light\\",
      "\\name:light\\",
      "\\title:light\\",
      "\\date:light\\",
    ],
    versionHistory: [
      { version: "v4.2", releasedAt: "2026-02-14", status: "current", author: "Sara Friis (counsel)", changeNote: "Current. Liability cap raised to €500k. UK addendum added post-Brexit. SLA exhibit clarified." },
      { version: "v4.1", releasedAt: "2025-11-14", status: "deprecated", deprecatedAt: "2026-02-14", author: "Sara Friis (counsel)", changeNote: "Indemnity clause tightened after Anderson Inc dispute. Customer-only indemnity now requires explicit Legal approval." },
      { version: "v4.0", releasedAt: "2025-08-22", status: "deprecated", deprecatedAt: "2025-11-14", author: "Sara Friis (counsel)", changeNote: "Major rewrite when Sara joined. Cleaner liability section, dedicated SLA exhibit, EU SCCs incorporated for GDPR." },
      { version: "v3.5", releasedAt: "2025-01-08", status: "archived", deprecatedAt: "2025-08-22", author: "Outside counsel", changeNote: "Pre-rewrite MSA used during company's first year. Two signed contracts still active on this version." },
    ],
  },
  {
    id: "order_form_v2_0",
    name: "Order Form",
    version: "v2.0",
    type: "Order Form",
    risk: "medium",
    ownerTeam: "Sales",
    jurisdictions: ["Denmark", "United Kingdom", "United States"],
    description:
      "Commercial line items and pricing against a signed MSA. Used for new deals, seat expansions, and tier upgrades.",
    clauseRules: [
      {
        key: "msa_reference",
        label: "Reference to executed MSA",
        expected: "Required",
        predicate: (f) => Boolean(f.referenceMsaId && f.referenceMsaId.length > 0),
        observed: (f) => f.referenceMsaId ?? "Not provided",
        severity: "block",
        reason: "Order Form must reference an executed MSA. If no MSA exists, route to MSA template first.",
      },
      {
        key: "order_total",
        label: "Order total (EUR)",
        expected: "Matches Salesforce / HubSpot deal value",
        predicate: () => true,
        observed: (f) => `€${(f.orderTotalEur ?? 0).toLocaleString()}`,
        severity: "info",
        reason: "Cross-check against the source deal record for typos.",
      },
      {
        key: "billing_frequency",
        label: "Billing frequency",
        expected: "Annual upfront (standard) or quarterly / monthly",
        predicate: (f) => ["annual", "quarterly", "monthly"].includes(f.billingFrequency ?? "annual"),
        observed: (f) => f.billingFrequency ?? "annual",
        severity: "info",
        reason: "Annual upfront is preferred for cash flow. Quarterly + monthly approved on case-by-case basis.",
      },
      {
        key: "payment_terms",
        label: "Payment terms",
        expected: "Net 30",
        predicate: (f) => (f.paymentTermsDays ?? 30) <= 30,
        observed: (f) => `Net ${f.paymentTermsDays ?? 30}`,
        severity: "warn",
        reason: "Standard is Net 30. Longer terms impact cash flow.",
      },
      {
        key: "term_months",
        label: "Order term",
        expected: "12 months (matches MSA initial term)",
        predicate: (f) => (f.termMonths ?? 12) <= 36,
        observed: (f) => `${f.termMonths ?? 12} months`,
        severity: "info",
        reason: "Order term typically matches the MSA term. Multi-year orders allowed with awareness.",
      },
    ],
    docusignFeatures: {
      qesRequired: false,
      smsVerification: false,
      witnessRequired: false,
      powerFormCapable: false,
      bulkSendCapable: false,
      expiryDays: 14,
      reminderDays: [3, 7],
      signingOrder: "sequential",
    },
    conditionalSections: [
      {
        id: "expansion_addendum",
        label: "Expansion Addendum (existing customer)",
        description: "Used when the Order Form is an expansion against an existing MSA. References prior orders.",
        appliesWhen: (f) => Boolean(f.referenceMsaId && /^msa_existing_/i.test(f.referenceMsaId)),
      },
    ],
    anchorTags: [
      "\\sig:counterparty\\",
      "\\name:counterparty\\",
      "\\title:counterparty\\",
      "\\date:counterparty\\",
      "\\sig:light\\",
      "\\date:light\\",
    ],
    versionHistory: [
      { version: "v2.0", releasedAt: "2026-03-04", status: "current", author: "Sara Friis (counsel)", changeNote: "Current. Restructured pricing table format. Added expansion addendum for orders against existing MSAs." },
      { version: "v1.3", releasedAt: "2025-10-12", status: "deprecated", deprecatedAt: "2026-03-04", author: "Sara Friis (counsel)", changeNote: "Added explicit MSA reference field. Required for all new Order Forms after this version." },
      { version: "v1.0", releasedAt: "2025-04-20", status: "archived", deprecatedAt: "2025-10-12", author: "Sara Friis (counsel)", changeNote: "First standalone Order Form template. Previously Order Form content was inlined in the MSA." },
    ],
  },
  {
    id: "employment_dk_v2_0",
    name: "Employment Contract (Denmark)",
    version: "v2.0",
    type: "Employment",
    risk: "medium",
    ownerTeam: "People Ops",
    jurisdictions: ["Denmark"],
    description:
      "Standard employment contract for hires at Light ApS. Governed by Danish Funktionærloven. UK hires use the separate UK template.",
    clauseRules: [
      {
        key: "probation",
        label: "Probation period",
        expected: "3 months",
        predicate: (f) => (f.probationMonths ?? 3) <= 3,
        observed: (f) => `${f.probationMonths ?? 3} months`,
        severity: "warn",
        reason: "Standard probation under Danish Funktionærloven is 3 months. Longer probation may not be enforceable.",
      },
      {
        key: "notice_period",
        label: "Notice period",
        expected: "1 month (Funktionærloven default)",
        predicate: () => true,
        observed: () => "1 month",
        severity: "info",
        reason: "Standard notice period under Danish law for first 6 months of employment.",
      },
      {
        key: "working_hours",
        label: "Working hours",
        expected: "37 hours / week",
        predicate: () => true,
        observed: () => "37 hours / week",
        severity: "info",
        reason: "Standard Danish working week is 37 hours.",
      },
      {
        key: "work_location",
        label: "Primary work location",
        expected: "Copenhagen office (hybrid)",
        predicate: (f) => /copenhagen/i.test(f.workLocation ?? "Copenhagen"),
        observed: (f) => f.workLocation ?? "Copenhagen",
        severity: "info",
        reason: "Default is Copenhagen hybrid. Remote-only or non-DK requires People Ops review.",
      },
      {
        key: "variable_comp",
        label: "Variable compensation",
        expected: "Sales: up to 50% / Other: 0%",
        predicate: (f) => {
          const isSales = /sales|account|revenue/i.test(f.role ?? "");
          if (isSales) return (f.variablePct ?? 50) <= 50;
          return (f.variablePct ?? 0) === 0;
        },
        observed: (f) => `${f.variablePct ?? 0}%`,
        severity: "warn",
        reason: "Standard variable compensation is 0% (non-sales) or up to 50% (sales). Exceptions require CFO approval.",
      },
      {
        key: "holiday_entitlement",
        label: "Holiday entitlement",
        expected: "25 days / year (Danish standard)",
        predicate: () => true,
        observed: () => "25 days / year",
        severity: "info",
        reason: "Danish Holiday Act minimum, plus 5 extra company days as Light standard.",
      },
    ],
    docusignFeatures: {
      qesRequired: false,
      smsVerification: true,
      witnessRequired: false,
      powerFormCapable: false,
      bulkSendCapable: false,
      expiryDays: 7,
      reminderDays: [2, 5],
      signingOrder: "sequential",
    },
    conditionalSections: [
      {
        id: "commission_plan",
        label: "Commission Plan Exhibit",
        description: "Detailed commission targets, accelerators, and payout schedule. Attached for sales roles only.",
        appliesWhen: (f) => /sales|account|revenue/i.test(f.role ?? ""),
      },
      {
        id: "ip_assignment",
        label: "IP Assignment Addendum",
        description: "Detailed intellectual property assignment for product and engineering roles.",
        appliesWhen: (f) => /engineer|product|design|research/i.test(f.role ?? ""),
      },
      {
        id: "equity_addendum",
        label: "Equity Grant Addendum",
        description: "Warrant or option grant terms attached when equity is included.",
        appliesWhen: (f) => (f.equityBps ?? 0) > 0,
      },
      {
        id: "non_compete",
        label: "Non-compete Addendum",
        description: "Limited non-compete for leadership roles per Danish law (compensated, max 12 months).",
        appliesWhen: (f) => /vp|director|head of|chief|c-level/i.test(f.role ?? ""),
      },
    ],
    anchorTags: [
      "\\sig:candidate\\",
      "\\date:candidate\\",
      "\\initial:candidate:p1\\",
      "\\initial:candidate:p2\\",
      "\\sig:light\\",
      "\\date:light\\",
    ],
    versionHistory: [
      { version: "v2.0", releasedAt: "2026-01-22", status: "current", author: "Pia Andersen + Sara Friis", changeNote: "Current. Updated for new variable comp plan + revised IP assignment language. Added equity grant addendum hook." },
      { version: "v1.4", releasedAt: "2025-07-15", status: "deprecated", deprecatedAt: "2026-01-22", author: "Pia Andersen + Sara Friis", changeNote: "Added probation period flexibility and Copenhagen-specific work location defaults." },
      { version: "v1.0", releasedAt: "2024-09-03", status: "archived", deprecatedAt: "2025-07-15", author: "Outside counsel", changeNote: "Original Funktionærloven-compliant template from the first wave of hires." },
    ],
  },
  {
    id: "warrant_v1_5",
    name: "Warrant Agreement",
    version: "v1.5",
    type: "Warrant",
    risk: "high",
    ownerTeam: "CFO",
    jurisdictions: ["Denmark"],
    description:
      "Equity warrant grant for advisors and board members. Always requires Legal, CFO, and Board approval. eIDAS QES required for a valid grant.",
    clauseRules: [
      {
        key: "vesting",
        label: "Vesting period",
        expected: "48 months",
        predicate: (f) => (f.vestingMonths ?? 48) >= 36,
        observed: (f) => `${f.vestingMonths ?? 48} months`,
        severity: "warn",
        reason: "Standard vesting is 48 months. Shorter than 36 months requires CFO and Board approval.",
      },
      {
        key: "cliff",
        label: "Cliff",
        expected: "12 months",
        predicate: (f) => (f.cliffMonths ?? 12) >= 12,
        observed: (f) => `${f.cliffMonths ?? 12} months`,
        severity: "warn",
        reason: "Standard cliff is 12 months. Shorter cliff requires explicit Board approval.",
      },
      {
        key: "board_resolution",
        label: "Board resolution reference",
        expected: "Required and confirmed before send",
        predicate: (f) => Boolean(f.boardResolutionRef && f.boardResolutionRef.length > 0 && !/pending/i.test(f.boardResolutionRef)),
        observed: (f) => f.boardResolutionRef ?? "Not yet recorded",
        severity: "block",
        reason: "Confirmed board resolution reference must be recorded before sending. Required for cap table audit.",
      },
      {
        key: "pool_capacity",
        label: "Warrant pool capacity",
        expected: "Within approved pool",
        predicate: (f) => (f.warrantPct ?? 0) <= 1.0,
        observed: (f) => `${f.warrantPct ?? 0}%`,
        severity: "warn",
        reason: "Grants above 1% to a single stakeholder require fresh Board approval beyond standing pool authority.",
      },
      {
        key: "acceleration",
        label: "Acceleration",
        expected: "None (standard) or single-trigger on change of control (advisors)",
        predicate: () => true,
        observed: () => "Standard (no acceleration)",
        severity: "info",
        reason: "Default is no acceleration. Single-trigger requires Board approval. Double-trigger reserved for senior leadership.",
      },
    ],
    docusignFeatures: {
      qesRequired: true,
      smsVerification: false,
      witnessRequired: true,
      powerFormCapable: false,
      bulkSendCapable: false,
      expiryDays: 30,
      reminderDays: [7, 14],
      signingOrder: "sequential",
    },
    conditionalSections: [
      {
        id: "board_resolution_exhibit",
        label: "Board Resolution (Exhibit A)",
        description: "Signed board resolution authorising the grant. Required attachment.",
        appliesWhen: () => true,
      },
      {
        id: "409a_exhibit",
        label: "Latest 409A Valuation (Exhibit B)",
        description: "Independent valuation establishing the exercise price.",
        appliesWhen: () => true,
      },
      {
        id: "acceleration_addendum",
        label: "Acceleration Addendum",
        description: "Single or double-trigger acceleration terms. Only attached when applicable.",
        appliesWhen: () => false,
      },
    ],
    anchorTags: [
      "\\sig:stakeholder\\",
      "\\date:stakeholder\\",
      "\\sig:cfo\\",
      "\\date:cfo\\",
      "\\sig:ceo\\",
      "\\date:ceo\\",
      "\\sig:witness\\",
      "\\date:witness\\",
    ],
    versionHistory: [
      { version: "v1.5", releasedAt: "2025-12-19", status: "current", author: "Sara Friis + Magnus (CFO)", changeNote: "Current. Tightened board resolution gate. Witness signer made mandatory for valid grant." },
      { version: "v1.4", releasedAt: "2025-05-30", status: "deprecated", deprecatedAt: "2025-12-19", author: "Outside counsel", changeNote: "Added eIDAS QES requirement for advisors and board members." },
      { version: "v1.0", releasedAt: "2024-11-08", status: "archived", deprecatedAt: "2025-05-30", author: "Outside counsel", changeNote: "First warrant template after the seed round. Used for the first 3 advisor grants." },
    ],
  },
  {
    id: "warrant_advisor_v1_0",
    name: "Advisor Warrant",
    version: "v1.0",
    type: "Warrant",
    risk: "medium",
    ownerTeam: "CFO",
    jurisdictions: ["Denmark", "United Kingdom"],
    description:
      "Lightweight warrant for individual advisors and consultants below 0.5% grant. Shorter 24-month vest, no witness required, simpler exhibits. Standing Board pool authority covers up to 0.5% per advisor without fresh resolution.",
    clauseRules: [
      {
        key: "vesting",
        label: "Vesting period",
        expected: "24 months (advisor standard)",
        predicate: (f) => (f.vestingMonths ?? 24) >= 12,
        observed: (f) => `${f.vestingMonths ?? 24} months`,
        severity: "warn",
        reason: "Advisor standard is 24 months. Anything shorter than 12 months requires CFO override.",
      },
      {
        key: "cliff",
        label: "Cliff",
        expected: "6 months",
        predicate: (f) => (f.cliffMonths ?? 6) >= 3,
        observed: (f) => `${f.cliffMonths ?? 6} months`,
        severity: "info",
        reason: "Advisor cliff is shorter (6 months) than employee warrants. Less than 3 months is non-standard.",
      },
      {
        key: "pool_capacity",
        label: "Advisor pool capacity",
        expected: "≤ 0.5% (covered by standing pool authority)",
        predicate: (f) => (f.warrantPct ?? 0) <= 0.5,
        observed: (f) => `${f.warrantPct ?? 0}%`,
        severity: "block",
        reason: "Advisor pool standing authority covers ≤ 0.5%. Higher grants must use the standard Warrant template (warrant_v1_5) and obtain fresh Board approval.",
      },
      {
        key: "board_resolution",
        label: "Board pool reference",
        expected: "Reference to standing pool resolution",
        predicate: (f) => Boolean(f.boardResolutionRef && f.boardResolutionRef.length > 0),
        observed: (f) => f.boardResolutionRef ?? "Standing pool resolution required",
        severity: "warn",
        reason: "Reference the standing advisor pool resolution (e.g. BR-2025-POOL-001) for audit trail.",
      },
      {
        key: "exercise_window",
        label: "Post-termination exercise window",
        expected: "90 days (standard) or up to 12 months",
        predicate: () => true,
        observed: () => "90 days (standard)",
        severity: "info",
        reason: "Default 90-day post-termination exercise. Up to 12 months supported via the Exercise Window Extension addendum.",
      },
    ],
    docusignFeatures: {
      qesRequired: true,
      smsVerification: false,
      witnessRequired: false,
      powerFormCapable: false,
      bulkSendCapable: false,
      expiryDays: 21,
      reminderDays: [5, 12],
      signingOrder: "sequential",
    },
    conditionalSections: [
      {
        id: "advisor_pool_resolution",
        label: "Standing Advisor Pool Resolution (Exhibit A)",
        description: "Reference to the standing board resolution authorising the advisor warrant pool. Single document covers all grants ≤ 0.5%.",
        appliesWhen: () => true,
      },
      {
        id: "409a_exhibit",
        label: "Latest 409A Valuation (Exhibit B)",
        description: "Independent valuation establishing the exercise price.",
        appliesWhen: () => true,
      },
      {
        id: "exercise_extension_addendum",
        label: "Exercise Window Extension Addendum",
        description: "Extends post-termination exercise window beyond 90 days. Attached only when negotiated.",
        appliesWhen: () => false,
      },
    ],
    anchorTags: [
      "\\sig:stakeholder\\",
      "\\date:stakeholder\\",
      "\\sig:cfo\\",
      "\\date:cfo\\",
      "\\sig:ceo\\",
      "\\date:ceo\\",
    ],
    versionHistory: [
      { version: "v1.0", releasedAt: "2026-03-12", status: "current", author: "Sara Friis + Magnus (CFO)", changeNote: "New template introduced to unblock advisor onboarding cadence. Standing pool authority eliminates per-grant Board resolution; eIDAS QES still required, witness signer dropped for advisors under 0.5%." },
    ],
  },
  {
    id: "msa_pilot_v1_0",
    name: "MSA: Pilot",
    formalName: "Master Services Agreement (Pilot)",
    version: "v1.0",
    type: "MSA",
    risk: "low",
    ownerTeam: "Sales",
    jurisdictions: ["Denmark", "United Kingdom", "United States"],
    description:
      "Short proof-of-concept agreement for customers evaluating Light. 3-month term, lower liability cap, no auto-renewal. Designed to move pilots quickly.",
    clauseRules: [
      {
        key: "term_months",
        label: "Pilot term",
        expected: "3 months",
        predicate: (f) => (f.termMonths ?? 3) <= 3,
        observed: (f) => `${f.termMonths ?? 3} months`,
        severity: "warn",
        reason: "Pilot term is fixed at 3 months. Longer pilots should convert to standard MSA.",
      },
      {
        key: "auto_renew",
        label: "Auto-renew",
        expected: "Off (pilots end, do not roll)",
        predicate: (f) => f.autoRenew === false,
        observed: (f) => (f.autoRenew === false ? "Off" : "On (non-standard for pilot)"),
        severity: "block",
        reason: "Pilots must not auto-renew. Customer must consciously commit via the standard MSA.",
      },
      {
        key: "liability_cap",
        label: "Liability cap (pilot scale)",
        expected: "€50,000",
        predicate: (f) => !f.liabilityCapUnlimited && (f.liabilityCapEur ?? 50_000) <= 50_000,
        observed: (f) => (f.liabilityCapUnlimited ? "Unlimited" : `€${(f.liabilityCapEur ?? 50_000).toLocaleString()}`),
        severity: "warn",
        reason: "Pilot agreements cap at €50k. Customers requesting more should convert to the full MSA template.",
      },
      {
        key: "payment_terms",
        label: "Payment terms",
        expected: "Net 30 or prepaid",
        predicate: (f) => (f.paymentTermsDays ?? 30) <= 30,
        observed: (f) => `Net ${f.paymentTermsDays ?? 30}`,
        severity: "info",
        reason: "Pilots typically prepaid or Net 30. Longer terms unusual at this scale.",
      },
      {
        key: "governing_law",
        label: "Governing law",
        expected: "Light entity jurisdiction (DK / UK / US)",
        predicate: (f) => /(denmark|germany|france|ireland|netherlands|sweden|finland|norway|spain|italy|united kingdom|england|uk|delaware|new york)/i.test(f.governingLaw ?? ""),
        observed: (f) => f.governingLaw ?? "Denmark",
        severity: "warn",
        reason: "Non-EU/UK/US governing law requires Legal review even for pilots.",
      },
    ],
    docusignFeatures: {
      qesRequired: false,
      smsVerification: false,
      witnessRequired: false,
      powerFormCapable: false,
      bulkSendCapable: false,
      expiryDays: 7,
      reminderDays: [2, 5],
      signingOrder: "sequential",
    },
    conditionalSections: [
      {
        id: "conversion_clause",
        label: "Conversion-to-MSA clause (auto-attached)",
        description: "Explains how the customer can convert to the full MSA at any time during or after the pilot.",
        appliesWhen: () => true,
      },
    ],
    anchorTags: [
      "\\sig:counterparty\\",
      "\\name:counterparty\\",
      "\\date:counterparty\\",
      "\\sig:light\\",
      "\\date:light\\",
    ],
    versionHistory: [
      { version: "v1.0", releasedAt: "2026-03-20", status: "current", author: "Sara Friis (counsel) + Tom Bauer (Sales lead)", changeNote: "Initial pilot template. Designed to compress legal review for POCs and trial customers." },
    ],
  },
  {
    id: "employment_uk_v1_0",
    name: "Employment Contract (United Kingdom)",
    version: "v1.0",
    type: "Employment",
    risk: "medium",
    ownerTeam: "People Ops",
    jurisdictions: ["United Kingdom"],
    description:
      "Employment contract for hires at Light Ltd. Governed by England and Wales law with UK statutory holiday, notice, and pension defaults.",
    clauseRules: [
      {
        key: "probation",
        label: "Probation period",
        expected: "6 months (UK standard)",
        predicate: (f) => (f.probationMonths ?? 6) <= 6,
        observed: (f) => `${f.probationMonths ?? 6} months`,
        severity: "warn",
        reason: "UK standard probation is 3-6 months. Longer probation may be challenged under UK employment law.",
      },
      {
        key: "notice_period",
        label: "Notice period",
        expected: "1 week during probation, then 1 month",
        predicate: () => true,
        observed: () => "1 week (probation) / 1 month (post-probation)",
        severity: "info",
        reason: "UK statutory minimum: 1 week during probation, then 1 month post-probation. Light pays above statutory after 2 years tenure.",
      },
      {
        key: "holiday_entitlement",
        label: "Holiday entitlement",
        expected: "28 days inclusive of bank holidays (UK statutory)",
        predicate: () => true,
        observed: () => "28 days (statutory) + 5 Light days = 33 days",
        severity: "info",
        reason: "UK Working Time Regulations require 28 days minimum. Light adds 5 company days as standard benefit.",
      },
      {
        key: "auto_enrolment_pension",
        label: "Pension auto-enrolment",
        expected: "Required (UK Pensions Act 2008)",
        predicate: () => true,
        observed: () => "Light contributes 5% employer, 3% employee minimum",
        severity: "info",
        reason: "Light Ltd must auto-enrol eligible employees in a qualifying workplace pension under UK law.",
      },
      {
        key: "work_location",
        label: "Primary work location",
        expected: "London office (hybrid)",
        predicate: (f) => /london|united kingdom|uk|england/i.test(f.workLocation ?? "London"),
        observed: (f) => f.workLocation ?? "London",
        severity: "info",
        reason: "Default for UK hires is London hybrid. Fully remote within UK acceptable. Outside UK requires People Ops review for tax + payroll implications.",
      },
      {
        key: "variable_comp",
        label: "Variable compensation",
        expected: "Sales: up to 50% / Other: 0%",
        predicate: (f) => {
          const isSales = /sales|account|revenue/i.test(f.role ?? "");
          if (isSales) return (f.variablePct ?? 50) <= 50;
          return (f.variablePct ?? 0) === 0;
        },
        observed: (f) => `${f.variablePct ?? 0}%`,
        severity: "warn",
        reason: "Same band logic as DK. Exceptions require CFO approval.",
      },
    ],
    docusignFeatures: {
      qesRequired: false,
      smsVerification: true,
      witnessRequired: false,
      powerFormCapable: false,
      bulkSendCapable: false,
      expiryDays: 7,
      reminderDays: [2, 5],
      signingOrder: "sequential",
    },
    conditionalSections: [
      {
        id: "commission_plan_uk",
        label: "Commission Plan Exhibit (UK)",
        description: "UK-specific commission terms with HMRC PAYE treatment. Attached for sales roles only.",
        appliesWhen: (f) => /sales|account|revenue/i.test(f.role ?? ""),
      },
      {
        id: "ip_assignment_uk",
        label: "IP Assignment Addendum (UK)",
        description: "UK Patents Act compliant IP assignment for product and engineering roles.",
        appliesWhen: (f) => /engineer|product|design|research/i.test(f.role ?? ""),
      },
      {
        id: "equity_addendum_uk",
        label: "Equity Grant Addendum (EMI eligible)",
        description: "UK-friendly equity terms via Enterprise Management Incentive scheme where eligible.",
        appliesWhen: (f) => (f.equityBps ?? 0) > 0,
      },
    ],
    anchorTags: [
      "\\sig:candidate\\",
      "\\date:candidate\\",
      "\\initial:candidate:p1\\",
      "\\initial:candidate:p2\\",
      "\\sig:light\\",
      "\\date:light\\",
    ],
    versionHistory: [
      { version: "v1.0", releasedAt: "2025-11-20", status: "current", author: "Sara Friis + UK counsel (Slaughter & May)", changeNote: "Initial UK employment template after Light Ltd was incorporated. Adapted from DK template with UK-specific statutory provisions." },
    ],
  },
];

/**
 * Rogue templates detected in Drive outside the canonical /Templates folder.
 * Production: a daily scan compares all docx files in shared Drives against
 * the master template set (by structural similarity + variable patterns), and
 * flags anything that looks like an MSA / NDA / etc. but is not the master.
 */
export const ROGUE_TEMPLATES: RogueTemplate[] = [
  {
    fileName: "MSA template - John's draft (LATEST).docx",
    driveFileId: "1xrogue_jK4mP9nQ2vR5sT8uW1yZ3aB6cD9eF",
    detectedAt: "2026-05-12T22:14:00Z",
    matchesTemplate: "msa_v4_2",
    similarity: 0.78,
    lastUsedBy: "John (Sales, left company Q4 2025)",
    lastUsedAt: "2025-12-04T14:20:00Z",
    diffSummary: "Based on MSA v4.0 (deprecated 2025-11). Liability cap modified to €100k. Custom-edited indemnity clause. No DPA exhibit.",
    recommendedAction: "Archive. John left in Q4 2025. Confirm with Tom (Sales) that no one is still referencing this file.",
  },
  {
    fileName: "MSA - modified for SecureBank.docx",
    driveFileId: "1xrogue_aB2cD4eF6gH8iJ0kL2mN4oP6qR8sT0",
    detectedAt: "2026-05-12T22:14:00Z",
    matchesTemplate: "msa_v4_2",
    similarity: 0.91,
    lastUsedBy: "Sara Lindberg (Sales)",
    lastUsedAt: "2026-03-18T11:42:00Z",
    diffSummary: "Based on MSA v4.1. Bespoke negotiated terms for SecureBank (Net 60, customer-only indemnity). Reused as draft for 2 other deals.",
    recommendedAction: "Block. Bespoke contracts must not be reused. Reroute Sara's new deals through master MSA v4.2.",
  },
  {
    fileName: "old_MSA.docx",
    driveFileId: "1xrogue_zY8xW6vU4tS2rQ0pO8nM6lK4jI2hG0",
    detectedAt: "2026-05-12T22:14:00Z",
    matchesTemplate: "msa_v4_2",
    similarity: 0.62,
    lastUsedAt: "2024-11-22T09:30:00Z",
    diffSummary: "MSA v3.5 (archived). No GDPR EU SCCs. Liability cap was €100k under prior policy. 18 months stale.",
    recommendedAction: "Archive. Move to /archive/2024 folder. Keep accessible for the 2 contracts still active on v3.5.",
  },
  {
    fileName: "Offer Letter v_FINAL_FINAL_use_this.docx",
    driveFileId: "1xrogue_qW1eR3tY5uI7oP9aS2dF4gH6jK8lM0",
    detectedAt: "2026-05-12T22:14:00Z",
    matchesTemplate: "employment_dk_v2_0",
    similarity: 0.74,
    lastUsedBy: "Anna (Recruiter)",
    lastUsedAt: "2026-04-08T16:55:00Z",
    diffSummary: "Based on Employment DK v1.4 (deprecated). Missing updated variable comp language. Missing IP assignment addendum.",
    recommendedAction: "Archive. Anna should switch all open offers to Employment DK v2.0. Ping Anna via Slack.",
  },
];

export const SOURCE_RECORDS: SourceRecord[] = [
  {
    id: "sr_acme",
    type: "deal",
    system: "Salesforce",
    externalRef: "Opp 00821",
    display: "Acme GmbH",
    subtitle: "€60k ARR · Closed Won · Standard terms · German entity",
    syncedAt: "2026-05-12T11:42:00Z",
    data: {
      counterpartyLegalName: "Acme GmbH",
      lightEntity: "Light ApS (Denmark)",
      contractValueEur: 60_000,
      paymentTermsDays: 30,
      liabilityCapEur: 500_000,
      indemnity: "mutual",
      governingLaw: "Denmark",
      termMonths: 12,
      autoRenew: true,
      dpaRequired: true,
      effectiveDate: "2026-06-01",
      counterpartySignerName: "Maria Holst",
      counterpartySignerEmail: "maria.holst@acme.gmbh",
      counterpartySignerTitle: "CFO",
    },
  },
  {
    id: "sr_bolt",
    type: "deal",
    system: "HubSpot",
    externalRef: "Deal 4421",
    display: "Bolt Industries Ltd",
    subtitle: "€180k ARR · UK customer · Net 60 + no cap + custom indemnity",
    syncedAt: "2026-05-12T09:18:00Z",
    data: {
      counterpartyLegalName: "Bolt Industries Ltd",
      lightEntity: "Light Ltd (United Kingdom)",
      contractValueEur: 180_000,
      paymentTermsDays: 60,
      liabilityCapUnlimited: true,
      indemnity: "customer_only",
      governingLaw: "England and Wales",
      termMonths: 24,
      autoRenew: true,
      dpaRequired: true,
      effectiveDate: "2026-06-15",
      counterpartySignerName: "James Whitfield",
      counterpartySignerEmail: "jw@bolt.com",
      counterpartySignerTitle: "Head of Procurement",
    },
  },
  {
    id: "sr_crescent",
    type: "deal",
    system: "Attio",
    externalRef: "rec_88x21",
    display: "Crescent Studios",
    subtitle: "Early-stage prospect · NDA only at this stage · Danish entity",
    syncedAt: "2026-05-11T16:02:00Z",
    data: {
      counterpartyLegalName: "Crescent Studios ApS",
      lightEntity: "Light ApS (Denmark)",
      governingLaw: "Denmark",
      termMonths: 24,
      counterpartySignerName: "Sara Lindquist",
      counterpartySignerEmail: "sara@crescent.studio",
      counterpartySignerTitle: "Founder",
    },
  },
  {
    id: "sr_linear",
    type: "deal",
    system: "Salesforce",
    externalRef: "Opp 00798",
    display: "Linear Software Inc",
    subtitle: "€48k ARR · Closed Won 2026-04-22 · Pre-signed example",
    syncedAt: "2026-04-22T10:00:00Z",
    data: {
      counterpartyLegalName: "Linear Software Inc",
      lightEntity: "Light Inc. (US Delaware)",
      contractValueEur: 48_000,
      paymentTermsDays: 30,
      liabilityCapEur: 500_000,
      indemnity: "mutual",
      governingLaw: "Delaware",
      termMonths: 12,
      effectiveDate: "2026-05-01",
    },
  },
  {
    id: "sr_jane",
    type: "candidate",
    system: "Personio",
    externalRef: "cand_2871",
    display: "Jane Sørensen",
    subtitle: "Senior Engineer · Copenhagen · €105k · Verbal accept",
    syncedAt: "2026-05-12T08:30:00Z",
    data: {
      candidateName: "Jane Sørensen",
      role: "Senior Engineer",
      salaryEur: 105_000,
      variablePct: 0,
      startDate: "2026-07-01",
      manager: "Alex Petersen",
      probationMonths: 3,
      workLocation: "Copenhagen (hybrid)",
    },
  },
  {
    id: "sr_marcus",
    type: "candidate",
    system: "Ashby",
    externalRef: "app_5512",
    display: "Marcus Lee",
    subtitle: "VP Sales · Copenhagen · €165k + 50% variable · Above band, has equity",
    syncedAt: "2026-05-12T07:55:00Z",
    data: {
      candidateName: "Marcus Lee",
      role: "VP Sales",
      salaryEur: 165_000,
      variablePct: 50,
      startDate: "2026-08-01",
      manager: "Jonathan Sanders",
      probationMonths: 3,
      workLocation: "Copenhagen (hybrid)",
      equityBps: 50,
    },
  },
  {
    id: "sr_anya",
    type: "stakeholder",
    system: "Manual entry",
    display: "Anya Petrov",
    subtitle: "Board advisor · 0.25% warrant grant · Vesting 48m / cliff 12m",
    syncedAt: "2026-05-10T14:20:00Z",
    data: {
      stakeholderName: "Anya Petrov",
      warrantPct: 0.25,
      vestingMonths: 48,
      cliffMonths: 12,
    },
  },
  {
    id: "sr_nordic_partner",
    type: "deal",
    system: "Attio",
    externalRef: "rec_a9b2x",
    display: "Nordic Cloud Partner ApS",
    subtitle: "Partner evaluation · Mutual NDA · Both sides exchange confidential info",
    syncedAt: "2026-05-12T13:15:00Z",
    data: {
      counterpartyLegalName: "Nordic Cloud Partner ApS",
      lightEntity: "Light ApS (Denmark)",
      governingLaw: "Denmark",
      termMonths: 24,
      counterpartySignerName: "Erik Lindgren",
      counterpartySignerEmail: "erik@nordiccloud.dk",
      counterpartySignerTitle: "CTO",
    },
  },
  {
    id: "sr_acme_expansion",
    type: "deal",
    system: "Salesforce",
    externalRef: "Opp 00847",
    display: "Acme GmbH, Q3 Expansion",
    subtitle: "€40k expansion · Order Form against existing MSA · 10 more seats + Analytics tier",
    syncedAt: "2026-05-12T11:55:00Z",
    data: {
      counterpartyLegalName: "Acme GmbH",
      lightEntity: "Light ApS (Denmark)",
      referenceMsaId: "MSA-Acme-2026-001",
      orderTotalEur: 40_000,
      paymentTermsDays: 30,
      billingFrequency: "annual",
      seatCount: 10,
      termMonths: 9,
      effectiveDate: "2026-06-01",
      counterpartySignerName: "Maria Holst",
      counterpartySignerEmail: "maria.holst@acme.gmbh",
      counterpartySignerTitle: "CFO",
    },
  },
  {
    id: "sr_cypher",
    type: "deal",
    system: "Salesforce",
    externalRef: "Opp 00855",
    display: "Cypher Labs ApS",
    subtitle: "€75k ARR · Closed Won · Net 45 requested (non-standard)",
    syncedAt: "2026-05-13T08:42:00Z",
    data: {
      counterpartyLegalName: "Cypher Labs ApS",
      lightEntity: "Light ApS (Denmark)",
      contractValueEur: 75_000,
      paymentTermsDays: 45,
      liabilityCapEur: 500_000,
      indemnity: "mutual",
      governingLaw: "Denmark",
      termMonths: 12,
      autoRenew: true,
      dpaRequired: true,
      effectiveDate: "2026-06-10",
      counterpartySignerName: "Lars Mikkelsen",
      counterpartySignerEmail: "lars@cypherlabs.dk",
      counterpartySignerTitle: "Co-founder",
    },
  },
  {
    id: "sr_pilot_studios",
    type: "deal",
    system: "HubSpot",
    externalRef: "Deal 5102",
    display: "Pilot Studios GmbH",
    subtitle: "€8k pilot · 3-month POC · Closed Won pilot stage",
    syncedAt: "2026-05-13T09:30:00Z",
    data: {
      counterpartyLegalName: "Pilot Studios GmbH",
      lightEntity: "Light ApS (Denmark)",
      contractValueEur: 8_000,
      paymentTermsDays: 30,
      liabilityCapEur: 50_000,
      indemnity: "mutual",
      governingLaw: "Denmark",
      termMonths: 3,
      autoRenew: false,
      dpaRequired: true,
      effectiveDate: "2026-05-20",
      counterpartySignerName: "Henrik Schmidt",
      counterpartySignerEmail: "henrik@pilotstudios.de",
      counterpartySignerTitle: "Co-founder",
    },
  },
  {
    id: "sr_quantum",
    type: "deal",
    system: "Salesforce",
    externalRef: "Opp 00811",
    display: "Quantum Analytics",
    subtitle: "€120k ARR · Closed Won 2026-05-02 · Standard terms · Pre-signed example",
    syncedAt: "2026-05-02T14:00:00Z",
    data: {
      counterpartyLegalName: "Quantum Analytics Ltd",
      lightEntity: "Light Ltd (United Kingdom)",
      contractValueEur: 120_000,
      paymentTermsDays: 30,
      liabilityCapEur: 500_000,
      indemnity: "mutual",
      governingLaw: "England and Wales",
      termMonths: 12,
      autoRenew: true,
      dpaRequired: true,
      effectiveDate: "2026-05-15",
      counterpartySignerName: "Priya Shah",
      counterpartySignerEmail: "priya@quantumanalytics.co.uk",
      counterpartySignerTitle: "CFO",
    },
  },
  {
    id: "sr_erin",
    type: "candidate",
    system: "Personio",
    externalRef: "cand_3104",
    display: "Erin O'Brien",
    subtitle: "Senior Designer · Copenhagen · €98k · Signed 2 days ago",
    syncedAt: "2026-05-09T10:20:00Z",
    data: {
      candidateName: "Erin O'Brien",
      role: "Senior Designer",
      salaryEur: 98_000,
      variablePct: 0,
      startDate: "2026-06-15",
      manager: "Alex Petersen",
      probationMonths: 3,
      workLocation: "Copenhagen (hybrid)",
    },
  },
  {
    id: "sr_oliver_uk",
    type: "candidate",
    system: "Personio",
    externalRef: "cand_3221",
    display: "Oliver Adekunle",
    subtitle: "Engineering Manager · London · £92k base · Signed 4 days ago",
    syncedAt: "2026-05-09T09:00:00Z",
    data: {
      candidateName: "Oliver Adekunle",
      role: "Engineering Manager",
      salaryEur: 105_000,
      variablePct: 0,
      startDate: "2026-07-01",
      manager: "Pia Andersen",
      probationMonths: 6,
      workLocation: "London (hybrid)",
      equityBps: 30,
    },
  },
];

const seedAt = (iso: string) => iso;

const RAW_SEEDS: Contract[] = [
  {
    id: "c_acme_msa",
    name: "Acme MSA",
    type: "MSA",
    templateId: "msa_v4_2",
    sourceRecordId: "sr_acme",
    counterparty: "Acme GmbH",
    owner: "Tom Bauer",
    ownerTeam: "Sales",
    valueEur: 60_000,
    risk: "medium",
    stage: "draft",
    createdAt: seedAt("2026-05-12T11:45:00Z"),
    updatedAt: seedAt("2026-05-12T11:45:00Z"),
    fields: SOURCE_RECORDS[0].data,
    audit: [
      { at: "2026-05-12T11:45:00Z", actor: "Tom Bauer (Sales)", event: "Contract created from Salesforce Opp 00821" },
    ],
  },
  {
    id: "c_bolt_msa",
    name: "Bolt MSA",
    type: "MSA",
    templateId: "msa_v4_2",
    sourceRecordId: "sr_bolt",
    counterparty: "Bolt Industries Ltd",
    owner: "Sara Lindberg",
    ownerTeam: "Sales",
    valueEur: 180_000,
    risk: "high",
    stage: "in_review",
    createdAt: seedAt("2026-05-11T15:30:00Z"),
    updatedAt: seedAt("2026-05-12T09:20:00Z"),
    fields: SOURCE_RECORDS[1].data,
    audit: [
      { at: "2026-05-11T15:30:00Z", actor: "Sara Lindberg (Sales)", event: "Contract created from HubSpot Deal 4421" },
      { at: "2026-05-11T15:30:30Z", actor: "system", event: "Clause check complete: 3 deviations flagged", meta: "Net 60, unlimited liability, customer-only indemnity" },
      { at: "2026-05-11T15:31:00Z", actor: "system", event: "Routed for approval: Legal, Head of Finance & Ops, CFO" },
      { at: "2026-05-11T15:31:10Z", actor: "system", event: "Slack DM sent to Sara Friis (Legal)" },
      { at: "2026-05-11T15:31:11Z", actor: "system", event: "Slack DM sent to Martina Holst (Head of Finance & Ops)" },
      { at: "2026-05-11T15:31:12Z", actor: "system", event: "Slack DM sent to Magnus Karlsson (CFO)" },
      { at: "2026-05-12T09:20:00Z", actor: "system", event: "Awaiting all three approvers" },
    ],
  },
  {
    id: "c_crescent_nda",
    name: "Crescent Studios NDA",
    type: "NDA",
    templateId: "nda_v3_1",
    sourceRecordId: "sr_crescent",
    counterparty: "Crescent Studios",
    owner: "Sara Lindberg",
    ownerTeam: "Sales",
    risk: "low",
    stage: "sent",
    createdAt: seedAt("2026-05-10T13:00:00Z"),
    updatedAt: seedAt("2026-05-10T14:15:00Z"),
    envelopeId: "DS-77812",
    fields: SOURCE_RECORDS[2].data,
    audit: [
      { at: "2026-05-10T13:00:00Z", actor: "Sara Lindberg (Sales)", event: "Contract created from Attio record" },
      { at: "2026-05-10T13:05:00Z", actor: "system", event: "Clause check complete: all standard" },
      { at: "2026-05-10T13:06:00Z", actor: "system", event: "No approvals required by routing rules" },
      { at: "2026-05-10T14:15:00Z", actor: "Sara Lindberg (Sales)", event: "Sent via DocuSign", meta: "Envelope DS-77812" },
      { at: "2026-05-10T14:17:00Z", actor: "system", event: "Slack DM sent to Sara: envelope delivered to counterparty" },
    ],
  },
  {
    id: "c_linear_msa",
    name: "Linear MSA",
    type: "MSA",
    templateId: "msa_v4_2",
    sourceRecordId: "sr_linear",
    counterparty: "Linear Software Inc",
    owner: "Tom Bauer",
    ownerTeam: "Sales",
    valueEur: 48_000,
    risk: "medium",
    stage: "filed",
    createdAt: seedAt("2026-04-22T10:15:00Z"),
    updatedAt: seedAt("2026-04-25T16:30:00Z"),
    signedAt: "2026-04-25T16:28:00Z",
    envelopeId: "DS-77620",
    fields: SOURCE_RECORDS[3].data,
    audit: [
      { at: "2026-04-22T10:15:00Z", actor: "Tom Bauer (Sales)", event: "Contract created from Salesforce Opp 00798" },
      { at: "2026-04-22T10:20:00Z", actor: "system", event: "Clause check complete: all standard" },
      { at: "2026-04-22T10:21:00Z", actor: "Martina Holst (Head of Finance & Ops)", event: "Auto-approved by standing rule", meta: "ARR < €100k, all clauses standard" },
      { at: "2026-04-22T10:25:00Z", actor: "Tom Bauer", event: "Sent via DocuSign", meta: "Envelope DS-77620" },
      { at: "2026-04-23T14:12:00Z", actor: "Linear (counterparty)", event: "Signed by counterparty" },
      { at: "2026-04-25T16:28:00Z", actor: "Jonathan Sanders (CEO)", event: "Signed by Light" },
      { at: "2026-04-25T16:30:00Z", actor: "system", event: "Filed to Drive, ledger updated", meta: "+€4,000 MRR booked" },
    ],
    ledger: {
      headline: "+€4,000 MRR booked to Linear Software Inc",
      rows: [
        { label: "MRR change", value: "+€4,000", note: "Light ledger entry #4398" },
        { label: "ARR", value: "€48,000" },
        { label: "Contract start", value: "01 May 2026", note: "Invoice schedule generated" },
        { label: "Renewal", value: "15 Mar 2027", note: "Calendar alert created" },
        { label: "Linked", value: "Salesforce Opp 00798", note: "Two-way sync established" },
      ],
    },
  },
  {
    id: "c_jane_offer",
    name: "Jane Sørensen offer",
    type: "Employment",
    templateId: "employment_dk_v2_0",
    sourceRecordId: "sr_jane",
    counterparty: "Jane Sørensen",
    owner: "Pia Andersen",
    ownerTeam: "People Ops",
    valueEur: 105_000,
    risk: "low",
    stage: "ready_to_send",
    createdAt: seedAt("2026-05-11T10:00:00Z"),
    updatedAt: seedAt("2026-05-11T11:30:00Z"),
    fields: SOURCE_RECORDS[4].data,
    audit: [
      { at: "2026-05-11T10:00:00Z", actor: "Pia Andersen (People Ops)", event: "Offer drafted from Personio candidate cand_2871" },
      { at: "2026-05-11T10:02:00Z", actor: "system", event: "Clause check complete: all standard" },
      { at: "2026-05-11T10:05:00Z", actor: "Pia Andersen (People Ops)", event: "Auto-approved (own role)", meta: "Salary within band, standard probation" },
      { at: "2026-05-11T11:30:00Z", actor: "system", event: "Ready to send. CEO countersignature required.", meta: "Awaiting send action by owner" },
    ],
  },
  {
    id: "c_marcus_offer",
    name: "Marcus Lee offer",
    type: "Employment",
    templateId: "employment_dk_v2_0",
    sourceRecordId: "sr_marcus",
    counterparty: "Marcus Lee",
    owner: "Pia Andersen",
    ownerTeam: "People Ops",
    valueEur: 165_000,
    risk: "medium",
    stage: "awaiting_approval",
    createdAt: seedAt("2026-05-10T09:00:00Z"),
    updatedAt: seedAt("2026-05-11T16:45:00Z"),
    fields: SOURCE_RECORDS[5].data,
    audit: [
      { at: "2026-05-10T09:00:00Z", actor: "Pia Andersen (People Ops)", event: "Offer drafted from Ashby app_5512" },
      { at: "2026-05-10T09:02:00Z", actor: "system", event: "Clause check complete. Salary above band for VP Sales." },
      { at: "2026-05-10T09:03:00Z", actor: "system", event: "Routing: People Ops + CFO + CEO (above-band, equity grant)" },
      { at: "2026-05-10T09:05:00Z", actor: "Pia Andersen (People Ops)", event: "Approved" },
      { at: "2026-05-10T09:06:00Z", actor: "system", event: "Slack DM sent to Magnus Karlsson (CFO)" },
      { at: "2026-05-11T16:45:00Z", actor: "system", event: "Awaiting CFO + CEO approval (28 hours pending)" },
    ],
  },
  {
    id: "c_anya_warrant",
    name: "Anya Petrov warrant",
    type: "Warrant",
    templateId: "warrant_v1_5",
    sourceRecordId: "sr_anya",
    counterparty: "Anya Petrov",
    owner: "Magnus Karlsson",
    ownerTeam: "Finance",
    risk: "high",
    stage: "awaiting_approval",
    createdAt: seedAt("2026-05-09T11:00:00Z"),
    updatedAt: seedAt("2026-05-12T08:00:00Z"),
    fields: { ...SOURCE_RECORDS[6].data, boardResolutionRef: "BR-2026-Q2-007 (pending)" },
    audit: [
      { at: "2026-05-09T11:00:00Z", actor: "Magnus Karlsson (CFO)", event: "Warrant draft created from stakeholder record" },
      { at: "2026-05-09T11:05:00Z", actor: "system", event: "Routing: Legal + CFO + Board (always for warrants)" },
      { at: "2026-05-09T11:06:00Z", actor: "Magnus Karlsson (CFO)", event: "Approved (self, as CFO initiated)" },
      { at: "2026-05-09T15:30:00Z", actor: "Sara Friis (external counsel)", event: "Approved via email magic link" },
      { at: "2026-05-12T08:00:00Z", actor: "system", event: "Awaiting Board resolution at next quarterly meeting" },
    ],
  },
  {
    id: "c_nordic_nda",
    name: "Nordic Cloud Partner NDA",
    type: "NDA",
    templateId: "nda_v3_1",
    sourceRecordId: "sr_nordic_partner",
    counterparty: "Nordic Cloud Partner ApS",
    owner: "Magnus Karlsson",
    ownerTeam: "Finance",
    risk: "low",
    stage: "ready_to_send",
    createdAt: seedAt("2026-05-12T13:20:00Z"),
    updatedAt: seedAt("2026-05-12T13:25:00Z"),
    fields: SOURCE_RECORDS.find((r) => r.id === "sr_nordic_partner")!.data,
    audit: [
      { at: "2026-05-12T13:20:00Z", actor: "Magnus Karlsson (CFO)", event: "Contract created from Attio record rec_a9b2x" },
      { at: "2026-05-12T13:20:05Z", actor: "system", event: "Clause check complete: all standard" },
      { at: "2026-05-12T13:20:06Z", actor: "system", event: "Routing: no approvals required (mutual NDA, standard terms)" },
      { at: "2026-05-12T13:25:00Z", actor: "system", event: "Ready to send via DocuSign" },
    ],
  },
  {
    id: "c_acme_expansion_order",
    name: "Acme GmbH Q3 Expansion Order",
    type: "Order Form",
    templateId: "order_form_v2_0",
    sourceRecordId: "sr_acme_expansion",
    counterparty: "Acme GmbH",
    owner: "Tom Bauer",
    ownerTeam: "Sales",
    valueEur: 40_000,
    risk: "low",
    stage: "awaiting_approval",
    createdAt: seedAt("2026-05-12T12:00:00Z"),
    updatedAt: seedAt("2026-05-12T12:10:00Z"),
    fields: SOURCE_RECORDS.find((r) => r.id === "sr_acme_expansion")!.data,
    audit: [
      { at: "2026-05-12T12:00:00Z", actor: "Tom Bauer (Sales)", event: "Order Form created from Salesforce Opp 00847" },
      { at: "2026-05-12T12:00:08Z", actor: "system", event: "Clause check complete: all standard" },
      { at: "2026-05-12T12:00:09Z", actor: "system", event: "Routing: Head of Finance & Ops awareness (≥ €25k)" },
      { at: "2026-05-12T12:00:10Z", actor: "system", event: "Slack DM sent to Martina Holst (Head of Finance & Ops)" },
      { at: "2026-05-12T12:10:00Z", actor: "system", event: "Awaiting Head of Finance & Ops auto-approval window" },
    ],
  },
  {
    id: "c_cypher_msa",
    name: "Cypher Labs MSA",
    type: "MSA",
    templateId: "msa_v4_2",
    sourceRecordId: "sr_cypher",
    counterparty: "Cypher Labs ApS",
    owner: "Sara Lindberg",
    ownerTeam: "Sales",
    valueEur: 75_000,
    risk: "medium",
    stage: "awaiting_approval",
    createdAt: seedAt("2026-05-13T08:45:00Z"),
    updatedAt: seedAt("2026-05-13T08:48:00Z"),
    fields: SOURCE_RECORDS.find((r) => r.id === "sr_cypher")!.data,
    audit: [
      { at: "2026-05-13T08:45:00Z", actor: "Sara Lindberg (Sales)", event: "Contract created from Salesforce Opp 00855" },
      { at: "2026-05-13T08:45:08Z", actor: "system", event: "Clause check complete: 1 deviation flagged (Net 45 vs Net 30)" },
      { at: "2026-05-13T08:45:09Z", actor: "system", event: "Routing: Head of Finance & Ops + Legal" },
      { at: "2026-05-13T08:45:10Z", actor: "system", event: "Slack DM sent to Martina Holst (Head of Finance & Ops)" },
      { at: "2026-05-13T08:45:11Z", actor: "system", event: "Slack DM sent to Sara Friis (Legal)" },
      { at: "2026-05-13T08:48:00Z", actor: "system", event: "Awaiting Head of Finance & Ops + Legal approval" },
    ],
  },
  {
    id: "c_pilot_studios_msa",
    name: "Pilot Studios MSA: Pilot",
    type: "MSA",
    templateId: "msa_pilot_v1_0",
    sourceRecordId: "sr_pilot_studios",
    counterparty: "Pilot Studios GmbH",
    owner: "Sara Lindberg",
    ownerTeam: "Sales",
    valueEur: 8_000,
    risk: "low",
    stage: "awaiting_approval",
    createdAt: seedAt("2026-05-13T09:35:00Z"),
    updatedAt: seedAt("2026-05-13T09:42:00Z"),
    fields: SOURCE_RECORDS.find((r) => r.id === "sr_pilot_studios")!.data,
    audit: [
      { at: "2026-05-13T09:35:00Z", actor: "Sara Lindberg (Sales)", event: "Pilot MSA created from HubSpot Deal 5102" },
      { at: "2026-05-13T09:35:08Z", actor: "system", event: "Clause check complete: all standard (3-month term, no auto-renew, €50k cap)" },
      { at: "2026-05-13T09:35:09Z", actor: "system", event: "Routing: Head of Finance & Ops (pilot revenue awareness)" },
      { at: "2026-05-13T09:35:10Z", actor: "system", event: "Slack DM sent to Martina Holst (Head of Finance & Ops)" },
      { at: "2026-05-13T09:42:00Z", actor: "system", event: "Awaiting Head of Finance & Ops approval" },
    ],
  },
  {
    id: "c_quantum_msa",
    name: "Quantum Analytics MSA",
    type: "MSA",
    templateId: "msa_v4_2",
    sourceRecordId: "sr_quantum",
    counterparty: "Quantum Analytics Ltd",
    owner: "Tom Bauer",
    ownerTeam: "Sales",
    valueEur: 120_000,
    risk: "medium",
    stage: "filed",
    createdAt: seedAt("2026-05-02T14:10:00Z"),
    updatedAt: seedAt("2026-05-08T11:42:00Z"),
    signedAt: "2026-05-08T11:40:00Z",
    envelopeId: "DS-77892",
    fields: SOURCE_RECORDS.find((r) => r.id === "sr_quantum")!.data,
    audit: [
      { at: "2026-05-02T14:10:00Z", actor: "Tom Bauer (Sales)", event: "Contract created from Salesforce Opp 00811" },
      { at: "2026-05-02T14:10:15Z", actor: "system", event: "Clause check complete: all standard" },
      { at: "2026-05-02T14:12:00Z", actor: "Martina Holst (Head of Finance & Ops)", event: "Auto-approved by standing rule (ARR €100k threshold met)" },
      { at: "2026-05-02T14:30:00Z", actor: "Magnus Karlsson (CFO)", event: "Approved (ARR > €100k requires CFO sign-off)" },
      { at: "2026-05-02T15:00:00Z", actor: "Tom Bauer", event: "Sent via DocuSign", meta: "Envelope DS-77892" },
      { at: "2026-05-05T09:14:00Z", actor: "Quantum Analytics (counterparty)", event: "Signed by counterparty" },
      { at: "2026-05-08T11:40:00Z", actor: "Jonathan Sanders (CEO)", event: "Signed by Light" },
      { at: "2026-05-08T11:42:00Z", actor: "system", event: "Filed to Drive, ledger updated", meta: "+€10,000 MRR booked" },
    ],
    ledger: {
      headline: "+€10,000 MRR booked to Quantum Analytics Ltd",
      rows: [
        { label: "MRR change", value: "+€10,000", note: "Light ledger entry #4456" },
        { label: "ARR", value: "€120,000" },
        { label: "Contract start", value: "15 May 2026", note: "Invoice schedule generated" },
        { label: "Renewal", value: "29 Mar 2027", note: "Calendar alert created (60-day notice)" },
        { label: "Light entity", value: "Light Ltd (UK)", note: "First UK customer this quarter" },
        { label: "Linked", value: "Salesforce Opp 00811", note: "Two-way sync established" },
      ],
    },
  },
  {
    id: "c_erin_offer",
    name: "Erin O'Brien offer",
    type: "Employment",
    templateId: "employment_dk_v2_0",
    sourceRecordId: "sr_erin",
    counterparty: "Erin O'Brien",
    owner: "Pia Andersen",
    ownerTeam: "People Ops",
    valueEur: 98_000,
    risk: "low",
    stage: "filed",
    createdAt: seedAt("2026-05-09T10:25:00Z"),
    updatedAt: seedAt("2026-05-11T16:12:00Z"),
    signedAt: "2026-05-11T16:10:00Z",
    envelopeId: "DS-77917",
    fields: SOURCE_RECORDS.find((r) => r.id === "sr_erin")!.data,
    audit: [
      { at: "2026-05-09T10:25:00Z", actor: "Pia Andersen (People Ops)", event: "Offer drafted from Personio candidate cand_3104" },
      { at: "2026-05-09T10:25:20Z", actor: "system", event: "Clause check complete: all standard" },
      { at: "2026-05-09T10:26:00Z", actor: "Pia Andersen (People Ops)", event: "Auto-approved (own role)" },
      { at: "2026-05-09T10:30:00Z", actor: "Pia Andersen", event: "Sent via DocuSign", meta: "Envelope DS-77917" },
      { at: "2026-05-09T11:45:00Z", actor: "Erin O'Brien (candidate)", event: "Signed by counterparty", meta: "SMS OTP verified" },
      { at: "2026-05-11T16:10:00Z", actor: "Jonathan Sanders (CEO)", event: "Signed by Light" },
      { at: "2026-05-11T16:12:00Z", actor: "system", event: "Filed, ledger updated", meta: "Headcount +1, payroll updated" },
    ],
    ledger: {
      headline: "Headcount +1: Erin O'Brien starts 15 Jun 2026",
      rows: [
        { label: "Role", value: "Senior Designer" },
        { label: "Base salary", value: "€98,000 annual" },
        { label: "Variable", value: "0%", note: "Fixed base only" },
        { label: "Start date", value: "15 Jun 2026", note: "Payroll record created" },
        { label: "Equity", value: "None", note: "No equity component" },
        { label: "Manager", value: "Alex Petersen" },
      ],
    },
  },
  {
    id: "c_oliver_uk_offer",
    name: "Oliver Adekunle offer (UK)",
    type: "Employment",
    templateId: "employment_uk_v1_0",
    sourceRecordId: "sr_oliver_uk",
    counterparty: "Oliver Adekunle",
    owner: "Pia Andersen",
    ownerTeam: "People Ops",
    valueEur: 105_000,
    risk: "low",
    stage: "filed",
    createdAt: seedAt("2026-05-09T09:05:00Z"),
    updatedAt: seedAt("2026-05-09T17:40:00Z"),
    signedAt: "2026-05-09T17:38:00Z",
    envelopeId: "DS-77925",
    fields: SOURCE_RECORDS.find((r) => r.id === "sr_oliver_uk")!.data,
    audit: [
      { at: "2026-05-09T09:05:00Z", actor: "Pia Andersen (People Ops)", event: "Offer drafted from Personio candidate cand_3221 (UK template)" },
      { at: "2026-05-09T09:05:18Z", actor: "system", event: "Clause check complete: all UK statutory provisions met" },
      { at: "2026-05-09T09:06:00Z", actor: "Pia Andersen (People Ops)", event: "Auto-approved (own role)" },
      { at: "2026-05-09T09:08:00Z", actor: "Jonathan Sanders (CEO)", event: "Approved equity grant (30 bps)" },
      { at: "2026-05-09T09:12:00Z", actor: "Pia Andersen", event: "Sent via DocuSign", meta: "Envelope DS-77925" },
      { at: "2026-05-09T10:30:00Z", actor: "Oliver Adekunle (candidate)", event: "Signed by counterparty", meta: "SMS OTP verified to UK mobile" },
      { at: "2026-05-09T17:38:00Z", actor: "Jonathan Sanders (CEO)", event: "Signed by Light Ltd" },
      { at: "2026-05-09T17:40:00Z", actor: "system", event: "Filed, ledger updated", meta: "Headcount +1 UK, payroll updated, EMI scheme eligibility flagged" },
    ],
    ledger: {
      headline: "Headcount +1: Oliver Adekunle starts 01 Jul 2026 (UK)",
      rows: [
        { label: "Role", value: "Engineering Manager" },
        { label: "Base salary", value: "€105,000 (≈ £92,000)", note: "Payroll record created in UK PAYE" },
        { label: "Equity", value: "30 bps", note: "EMI scheme eligibility check queued" },
        { label: "Start date", value: "01 Jul 2026", note: "Auto-enrolment pension at 3 months" },
        { label: "Light entity", value: "Light Ltd (UK)", note: "Second UK hire this quarter" },
        { label: "Manager", value: "Pia Andersen" },
      ],
    },
  },
];

/**
 * Pre-compute clauseResults and approvals for non-draft contracts so
 * the detail page renders meaningful data on first open. Pure function,
 * runs once at module load.
 */
function hydrate(c: Contract): Contract {
  const template = TEMPLATES.find((t) => t.id === c.templateId);
  if (!template) return c;
  // Pin templateVersion for every seed contract so the live-vs-pinned banner
  // logic on the detail page exercises the same code path as real contracts.
  const pinned = { ...c, templateVersion: c.templateVersion ?? template.version };
  if (pinned.stage === "draft") return pinned;
  const clauseResults = runChecks(template, pinned.fields);
  const approvals = computeRouting(template, pinned.fields, clauseResults);
  return { ...pinned, clauseResults, approvals };
}

export const SEED_CONTRACTS: Contract[] = RAW_SEEDS.map(hydrate);

export function getTemplate(id: string): Template | undefined {
  return TEMPLATES.find((t) => t.id === id);
}

export function getSourceRecord(id: string): SourceRecord | undefined {
  return SOURCE_RECORDS.find((r) => r.id === id);
}
